### ISSUE TITLE
Wrong path on MacOS

### ISSUE THREAD

**Issue by emilecantin** [roddhjav/pass-audit#2]
I followed the installation instructions for MacOS, and when I try running `pass audit`, I get:

```
\e[1;31m[x]\e[0m \e[1mError:\e[0m pass audit requires /usr/lib/password-store/audit/audit.py
```

The installation process installed this file, altough in `/usr/local/lib`, not `/usr/lib`.

**Comment by roddhjav** [comment]
Hi, you're right, I forgot to support OSX in the Makefile. It should be fixed now.
