### ISSUE TITLE
Check for duplicate / re-used passwords

### ISSUE THREAD

**Issue by matrss** [roddhjav/pass-audit#22]
Hey,
first of all, thanks for the great project!

I guess the title is pretty self-explanatory: it would be great if the passwords were also checked for duplicates, as it's best practice to not re-use passwords.

Off the top of my head and without diving into the codebase, I think this feature would pose 2 immediate challenges:
1. All passwords need to be hashed upfront and kept in memory to provide somewhat reasonable speed. This might be an issue for VERY large password-store's, but should generally be fine and could also be opt-in/-out.
2. What happens if only a subset of the password-store is audited. In this case, I think it's fine to also use the same subset to search for duplicates, as the user specifically requested not to touch the rest.

**Comment by roddhjav** [comment]
Hi, it is a nice proposal. I will work on it once I get some time.
