### ISSUE TITLE
Not working on Mac OS X

### ISSUE THREAD

**Issue by ghost** [roddhjav/pass-audit#23]
Unsure as to what is going on here. The extension doesn't load in the shell? After running the commands from the `README.md`, relaunching the shell and then typing `pass audit` results in the following

```bash
Error: audit is not in the password store.
```

**Comment by roddhjav** [comment]
Like any pass extension if you did not install it as a system extension, you need to set `PASSWORD_STORE_ENABLE_EXTENSIONS`  to 'true' for the extension to be enabled.

**Comment by tmytro** [comment]
Same problem. Other extensions are working well. MacBook Air M1.
<img width="328" alt="image" src="https://user-images.githubusercontent.com/40320374/123022096-2a844500-d3cd-11eb-8e2e-dddb9dcd2c17.png">

**Comment by tmytro** [comment]
@WayOfTheNet  You need to link `audit.bash` file in .password-store/.extensions folder.
