### ISSUE TITLE
About Debian packaging

### ISSUE THREAD

**Issue by thperret** [roddhjav/pass-audit#27]
Hi,

First let me say (again, see #25) what a nice software pass-audit is, so thanks for that.

I'm a Debian Maintainer and I plan to package pass-audit for Debian.

I'm facing a delicate issue with packaging your software because of your effort to make a Debian packaging. Basically, Debian [generally expect that the upstream release doesn't include a debian/ folder](https://wiki.debian.org/UpstreamGuide#Pristine_Upstream_Source).

So I'm kindly asking if you would consider keeping this folder out of the (next) release tarballs?
I realize this could disrupt your release workflow but that would ease mine.

Thanks.

Cheers,
Thomas

**Comment by roddhjav** [comment]
Thank for the hint to this debian doc, I did not know it. I will ensure to not include the debian directory in the next release tarballs

**Comment by roddhjav** [comment]
Release done, I excluded the debian folder from the release talbar see: https://github.com/roddhjav/pass-audit/releases/tag/v1.2
